apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: model-scaler
  namespace: house-price-predictor
spec:
  scaleTargetRef:
    name: house-price-model
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    # 1️⃣ Latency-based scaling (P95)
    - type: prometheus
      metadata:
        serverAddress: http://prom-kube-prometheus-stack-prometheus.monitoring.svc:9090
        metricName: fastapi_latency_p95
        query: |
          histogram_quantile(
            0.95,
            sum(
              rate(http_request_duration_seconds_bucket{app="model-svc"}[1m])
            ) by (le)
          )
        threshold: "0.5"

    # 2️⃣ RPS-based scaling
    - type: prometheus
      metadata:
        serverAddress: http://prom-kube-prometheus-stack-prometheus.monitoring.svc:9090
        metricName: fastapi_rps
        query: |
          sum(rate(http_requests_total[1m]))
        threshold: "1000"
