apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - model-deployment.yaml
  - model-svc.yaml
  - streamlit-ui-dep.yaml
  - streamlit-ui-svc.yaml
  - fast-api-scaledobject.yaml

