apiVersion: v1
kind: Service
metadata:
  name: model-svc
  namespace: house-price-predictor
  labels:
    app: model-svc
spec:
  type: NodePort
  selector:
    app: house-price-model
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30031