apiVersion: v1
kind: Service
metadata:
  name: streamlitui-svc
  namespace: house-price-predictor
spec:
  type: NodePort
  selector:
    app: house-price-ui
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30051