name: ML workflow

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch: {}

jobs:
  ml-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Set up the environment
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.14'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install uv
        uv venv .venv
        source .venv/bin/activate
        uv pip install -r requirements.txt

    # STAGE 1: DATA PROCESSING
    
    - name: Data Processing
      run: |
        source .venv/bin/activate
        python src/data/run_processing.py \
          --input data/raw/house_data.csv \
          --output data/processed/cleaned_house_data.csv

    # STAGE 2: FEATURE ENGINEERING
    
    - name: Feature Engineering
      run: |
        source .venv/bin/activate
        python src/features/engineer.py \
          --input data/processed/cleaned_house_data.csv \
          --output data/processed/featured_house_data.csv \
          --preprocessor models/trained/preprocessor.pkl

    # STAGE 3: MODEL TRAINING
    - name: Start MLflow Server
      run: |
        docker run -d \
          -p 5555:5000 \
          --name mlflow \
          ghcr.io/mlflow/mlflow:latest \
          mlflow server \
            --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

    - name: Train Model
      run: |
        source .venv/bin/activate
        python src/models/train_model.py \
          --config configs/model_config.yaml \
          --data data/processed/featured_house_data.csv \
          --models-dir models \
          --mlflow-tracking-uri http://localhost:5555

    - name: Stop MLflow Server
      run: |
        docker stop mlflow
        docker rm mlflow

  
    # STAGE 4: CONTAINERIZATION & PUSH
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build & push REST API image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: sauravkarki/housepricepredictor-restapi:${{ github.sha }}

    - name: Build & push Streamlit image
      uses: docker/build-push-action@v6
      with:
        context: streamlit_app
        file: streamlit_app/Dockerfile
        push: true
        tags: sauravkarki/housepricepredictor-streamlit:${{ github.sha }}
